// winter1.ysc @ L64319
void func_1641()
{
  if (IntToFloat(ENTITY::GET_ENTITY_HEALTH(Global_35)) < 150f)
  {
    if (PLAYER::_0x22CD23BB0C45E0CD(PLAYER::PLAYER_ID()) < 1f)
    {
      PLAYER::SET_PLAYER_HEALTH_RECHARGE_MULTIPLIER(PLAYER::PLAYER_ID(), 1f);
    }
  }
  else if (PLAYER::_0x22CD23BB0C45E0CD(PLAYER::PLAYER_ID()) > 0f)
  {
    PLAYER::SET_PLAYER_HEALTH_RECHARGE_MULTIPLIER(PLAYER::PLAYER_ID(), 0f);
  }
}