// ambush_inb_forest.ysc @ L9935
void func_321()
{
  if (!func_131(&Local_274, 256))
  {
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_SPRINT"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_JUMP"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_MOVE_LR"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_MOVE_UD"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_MOVE_UP_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_MOVE_DOWN_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_MOVE_LEFT_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_MOVE_RIGHT_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_VEH_ACCELERATE"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_MOVE_LR"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_MOVE_UD"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_MOVE_UP_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_MOVE_DOWN_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_MOVE_LEFT_ONLY"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_SPRINT"), false);
    PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_JUMP"), false);
    if (Local_274.f_5 < 2)
    {
      PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_EXIT"), false);
    }
  }
  else
  {
    PAD::ENABLE_CONTROL_ACTION(0, joaat("INPUT_SPRINT"), true);
    PAD::ENABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_SPRINT"), true);
    PAD::ENABLE_CONTROL_ACTION(0, joaat("INPUT_HORSE_JUMP"), true);
  }
}