// rcm_sadie11.ysc @ L27078
void func_828(int iParam0, int iParam1, var uParam2)
{
  int iVar0;

  PED::SET_PED_COMBAT_ATTRIBUTES(*iParam0, 0, true);
  PED::SET_PED_COMBAT_ATTRIBUTES(*iParam0, 3, true);
  PED::SET_PED_COMBAT_ATTRIBUTES(*iParam0, 5, true);
  PED::SET_PED_COMBAT_ATTRIBUTES(*iParam0, 42, false);
  PED::SET_PED_COMBAT_ATTRIBUTES(*iParam0, 44, true);
  PED::SET_PED_COMBAT_ATTRIBUTES(*iParam0, 35, true);
  TASK::_0x50AA09A0DA64E73C(*iParam0, VOLUME::_GET_VOLUME_COORDS(*iParam1), vLocal_973);
  PED::SET_PED_SPHERE_DEFENSIVE_AREA(*iParam0, VOLUME::_GET_VOLUME_COORDS(*iParam1), 2f, 0, 0, 0);
  PED::SET_PED_CONFIG_FLAG(*iParam0, 248, false);
  PED::SET_PED_CONFIG_FLAG(*iParam0, 397, true);
  PED::SET_BLOCKING_OF_NON_TEMPORARY_EVENTS(*iParam0, true);
  PED::SET_COMBAT_FLOAT(*iParam0, 0, 0.25f);
  PED::SET_COMBAT_FLOAT(*iParam0, 1, 3f);
  PED::SET_COMBAT_FLOAT(*iParam0, 2, 70f);
  PED::SET_COMBAT_FLOAT(*iParam0, 3, 1.25f);
  PED::SET_COMBAT_FLOAT(*iParam0, 4, 4f);
  TASK::OPEN_SEQUENCE_TASK(&iVar0);
  TASK::TASK_PUT_PED_DIRECTLY_INTO_COVER(*iParam0, VOLUME::_GET_VOLUME_COORDS(*iParam1), -1, 1, 0f, 1, 0, *uParam2, 1, 0, 0);
  TASK::TASK_COMBAT_HATED_TARGETS(0, -1f);
  TASK::CLOSE_SEQUENCE_TASK(iVar0);
  TASK::TASK_PERFORM_SEQUENCE(*iParam0, iVar0);
  TASK::CLEAR_SEQUENCE_TASK(&iVar0);
  PED::REGISTER_HATED_TARGETS_AROUND_PED(*iParam0, 500f);
}