// mudtown3b.ysc @ L17565
void func_164()
{
  PED::CLEAR_RELATIONSHIP_BETWEEN_GROUPS(6, joaat("REL_GANG_DUTCHS"), joaat("REL_COP"));
  PED::CLEAR_RELATIONSHIP_BETWEEN_GROUPS(6, joaat("REL_COP"), joaat("REL_GANG_DUTCHS"));
  PED::CLEAR_RELATIONSHIP_BETWEEN_GROUPS(6, joaat("REL_COMPANION_GROUP"), joaat("REL_COP"));
  PED::CLEAR_RELATIONSHIP_BETWEEN_GROUPS(6, joaat("REL_COP"), joaat("REL_COMPANION_GROUP"));
  PED::CLEAR_RELATIONSHIP_BETWEEN_GROUPS(6, joaat("REL_PLAYER_ALLY"), joaat("REL_COP"));
  PED::CLEAR_RELATIONSHIP_BETWEEN_GROUPS(6, joaat("REL_COP"), joaat("REL_PLAYER_ALLY"));
}