// abigail2_1.ysc @ L14497
void func_41(bool bParam0)
{
  if (bParam0)
  {
  }
  MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(15, bParam0);
  MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(6, bParam0);
  MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(1, bParam0);
}