// beechers_cow.ysc @ L618
void func_10()
{
  STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(joaat("A_C_COW"));
  STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(joaat("P_STOOL02X"));
  STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(joaat("S_BUCKETMILK01X"));
  STREAMING::REMOVE_CLIP_SET("CLIPSET@MINI_GAMES@STORY@MAR5@MILK_COW");
  STREAMING::_REMOVE_MOVE_NETWORK_DEF("script_mar5_milkcow_cow");
}