// mudtown5.ysc @ L61264
void func_1395(int iParam0)
{
  FLOCK::SET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 107, (FLOCK::GET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 91) * 1.5f));
  FLOCK::SET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 85, (FLOCK::GET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 91) * 1.5f));
  FLOCK::SET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 103, (FLOCK::GET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 86) * 1.5f));
  FLOCK::SET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 81, (FLOCK::GET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 86) * 1.5f));
  FLOCK::SET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 104, (FLOCK::GET_SPECIES_TUNING_FLOAT_PARAM(iParam0, 1, 87) * 1.5f));
}