// beat_coach_robbery.ysc @ L2265
void func_50(bool bParam0)
{
  if (!ENTITY::IS_ENTITY_DEAD(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 1)))
  {
    PED::SET_PED_NAME_DEBUG(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 1), "DRAFT_HARNESS_RR");
    FLOCK::SET_ANIMAL_TUNING_BOOL_PARAM(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 1), 48, bParam0);
  }
  if (!ENTITY::IS_ENTITY_DEAD(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 0)))
  {
    PED::SET_PED_NAME_DEBUG(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 0), "DRAFT_HARNESS_LR");
    FLOCK::SET_ANIMAL_TUNING_BOOL_PARAM(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 0), 48, bParam0);
  }
  if (!ENTITY::IS_ENTITY_DEAD(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 5)))
  {
    PED::SET_PED_NAME_DEBUG(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 5), "DRAFT_HARNESS_RF");
    FLOCK::SET_ANIMAL_TUNING_BOOL_PARAM(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 5), 48, bParam0);
  }
  if (!ENTITY::IS_ENTITY_DEAD(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 4)))
  {
    PED::SET_PED_NAME_DEBUG(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 4), "DRAFT_HARNESS_LF");
    FLOCK::SET_ANIMAL_TUNING_BOOL_PARAM(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 4), 48, bParam0);
  }
  if (!ENTITY::IS_ENTITY_DEAD(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 2)))
  {
    PED::SET_PED_NAME_DEBUG(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 2), "DRAFT_HARNESS_LM");
    FLOCK::SET_ANIMAL_TUNING_BOOL_PARAM(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 2), 48, bParam0);
  }
  if (!ENTITY::IS_ENTITY_DEAD(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 3)))
  {
    PED::SET_PED_NAME_DEBUG(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 3), "DRAFT_HARNESS_RM");
    FLOCK::SET_ANIMAL_TUNING_BOOL_PARAM(VEHICLE::_GET_PED_IN_DRAFT_SEAT(iLocal_606, 3), 48, bParam0);
  }
}