// abigail2_1.ysc @ L31916
void func_665()
{
  if (UNLOCK::_UNLOCK_IS_UNLOCKED(joaat("SP_GAME_CONTENT_PC_TIMED_EXCLUSIVE")))
  {
    return;
  }
  if (MISC::IS_PC_VERSION() || MISC::_IS_STADIA_VERSION())
  {
    UNLOCK::_UNLOCK_SET_UNLOCKED(joaat("SP_GAME_CONTENT_PC_TIMED_EXCLUSIVE"), true);
  }
  if (MISC::IS_ORBIS_VERSION())
  {
    UNLOCK::_UNLOCK_SET_UNLOCKED(joaat("SP_GAME_CONTENT_PC_TIMED_EXCLUSIVE"), true);
  }
  if (MISC::IS_DURANGO_VERSION())
  {
    UNLOCK::_UNLOCK_SET_UNLOCKED(joaat("SP_GAME_CONTENT_PC_TIMED_EXCLUSIVE"), true);
  }
}