// rcm_dusters62.ysc @ L8765
void func_310()
{
  if (WEAPON::_HAS_PED_GOT_WEAPON_COMPONENT(Local_29, joaat("COMPONENT_REPEATER_CLOTH_STRAP01"), joaat("WEAPON_SHOTGUN_DOUBLEBARREL")))
  {
    WEAPON::_REMOVE_WEAPON_COMPONENT_FROM_PED(Local_29, joaat("COMPONENT_REPEATER_CLOTH_STRAP01"), joaat("WEAPON_SHOTGUN_DOUBLEBARREL"));
  }
  if (WEAPON::_HAS_PED_GOT_WEAPON_COMPONENT(Local_29, joaat("COMPONENT_LEFTSHOULDER_STRAP01"), joaat("WEAPON_SHOTGUN_DOUBLEBARREL")))
  {
    WEAPON::_REMOVE_WEAPON_COMPONENT_FROM_PED(Local_29, joaat("COMPONENT_LEFTSHOULDER_STRAP01"), joaat("WEAPON_SHOTGUN_DOUBLEBARREL"));
  }
  if (WEAPON::_HAS_PED_GOT_WEAPON_COMPONENT(Local_29, joaat("COMPONENT_REPEATER_STRAP01"), joaat("WEAPON_SHOTGUN_DOUBLEBARREL")))
  {
    WEAPON::_REMOVE_WEAPON_COMPONENT_FROM_PED(Local_29, joaat("COMPONENT_REPEATER_STRAP01"), joaat("WEAPON_SHOTGUN_DOUBLEBARREL"));
  }
}