// act_caunc_rustling.ysc @ L32577
int func_803()
{
  if (PED::ADD_RELATIONSHIP_GROUP("Rustlers", &iLocal_1168) && PED::ADD_RELATIONSHIP_GROUP("Rancher", &iLocal_1169))
  {
    PED::SET_RELATIONSHIP_BETWEEN_GROUPS(6, iLocal_1168, iLocal_1169);
    PED::SET_RELATIONSHIP_BETWEEN_GROUPS(6, iLocal_1169, iLocal_1168);
    PED::SET_RELATIONSHIP_BETWEEN_GROUPS(6, iLocal_1169, PED::GET_PED_RELATIONSHIP_GROUP_HASH(Global_35));
    PED::SET_RELATIONSHIP_BETWEEN_GROUPS(6, PED::GET_PED_RELATIONSHIP_GROUP_HASH(Global_35), iLocal_1169);
    PED::SET_RELATIONSHIP_BETWEEN_GROUPS(6, iLocal_1168, PED::GET_PED_RELATIONSHIP_GROUP_HASH(Global_35));
    PED::SET_RELATIONSHIP_BETWEEN_GROUPS(6, PED::GET_PED_RELATIONSHIP_GROUP_HASH(Global_35), iLocal_1168);
    return 1;
  }
  return 0;
}