// interactive_campfire.ysc @ L17529
void func_540(var uParam0)
{
  if (HUD::_DOES_TEXT_DATABASE_EXIST(&(uParam0->f_17)))
  {
    HUD::_TEXT_DATABASE_REQUEST(&(uParam0->f_17));
  }
  STREAMING::REQUEST_ANIM_DICT("MECH_INVENTORY@CRAFTING@FALLBACKS@IN_HAND@MALE_A");
  STREAMING::REQUEST_MODEL(joaat("S_AMMO_RIFLE"), false);
  STREAMING::REQUEST_MODEL(joaat("S_AMMO_REPEATER"), false);
  STREAMING::REQUEST_MODEL(joaat("S_AMMO_45MM"), false);
  STREAMING::REQUEST_MODEL(joaat("S_AMMO_9MM"), false);
  STREAMING::REQUEST_MODEL(joaat("S_AMMO_SHOTGUN"), false);
  STREAMING::REQUEST_MODEL(joaat("S_CFT_ARROW"), false);
  STREAMING::REQUEST_MODEL(joaat("W_MELEE_TOMAHAWK01"), false);
  STREAMING::REQUEST_MODEL(joaat("W_MELEE_KNIFE05"), false);
  STREAMING::REQUEST_MODEL(joaat("P_CS_RAG01X"), false);
  STREAMING::REQUEST_MODEL(joaat("S_CFT_MOLOTOV01"), false);
  STREAMING::REQUEST_MODEL(joaat("S_CFT_MOLOTOV02"), false);
  STREAMING::REQUEST_MODEL(joaat("P_MOLOTOVEMPTY01X"), false);
  STREAMING::REQUEST_MODEL(joaat("W_STICK_DYNAMITE01"), false);
  func_851(uParam0);
  TXD::REQUEST_STREAMED_TEXTURE_DICT("satchel_textures", false);
  if (uParam0->f_31)
  {
    STREAMING::REQUEST_MODEL(joaat("P_WHITEFISHFILET01XB"), false);
    STREAMING::REQUEST_MODEL(joaat("P_REDFISHFILET01XB"), false);
    STREAMING::REQUEST_MODEL(joaat("P_WHITEFLESHYMEAT01XB"), false);
    STREAMING::REQUEST_MODEL(joaat("P_REDBIRDBREAST01XB"), false);
    STREAMING::REQUEST_MODEL(joaat("P_REDEFLESHYMEAT01XB"), false);
  }
}