// property_use_core.ysc @ L8885
void func_351()
{
  LAW::_0xD6C0A8C7C0B2F82C(PLAYER::PLAYER_ID(), 1);
  ENTITY::SET_ENTITY_INVINCIBLE(PLAYER::PLAYER_PED_ID(), false);
  PLAYER::SET_EVERYONE_IGNORE_PLAYER(PLAYER::PLAYER_ID(), false);
  PLAYER::SET_PLAYER_CAN_BE_HASSLED_BY_GANGS(PLAYER::PLAYER_ID(), true);
  PLAYER::SET_PLAYER_CONTROL(PLAYER::PLAYER_ID(), true, 0, false);
  func_101(&Global_1935630, 16384);
}