// gang3.ysc @ L51154
void func_1261()
{
  PED::_0xAB0D553FE20A6E25(0f);
  VEHICLE::SET_VEHICLE_DENSITY_MULTIPLIER_THIS_FRAME(0f);
  PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_VEH_EXIT"), false);
  PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_VEH_AIM"), false);
  PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_VEH_ATTACK"), false);
  PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_ATTACK"), false);
  PAD::DISABLE_CONTROL_ACTION(0, joaat("INPUT_AIM"), false);
  PAD::SET_INPUT_EXCLUSIVE(0, joaat("INPUT_VEH_DUCK"));
}