// finale_heist_prepa.ysc @ L37939
void func_396()
{
  PED::REMOVE_RELATIONSHIP_GROUP(iLocal_481);
  func_407(1);
  if (OBJECT::IS_DOOR_REGISTERED_WITH_SYSTEM(Global_41132[13 /*31*/]))
  {
    AUDIO::SET_SCRIPT_UPDATE_DOOR_AUDIO(Global_41132[13 /*31*/], false);
  }
  OBJECT::DOOR_SYSTEM_SET_OPEN_RATIO(Global_41132[13 /*31*/], 0f, true, true);
  OBJECT::DOOR_SYSTEM_SET_DOOR_STATE(Global_41132[13 /*31*/], 4, true, true);
  OBJECT::DOOR_SYSTEM_SET_DOOR_STATE(iLocal_369, 0, true, false);
  OBJECT::REMOVE_DOOR_FROM_SYSTEM(iLocal_369);
  PED::REMOVE_SCENARIO_BLOCKING_AREA(iLocal_360, false);
  func_55();
  PLAYER::SET_MAX_WANTED_LEVEL(5);
  PLAYER::SET_WANTED_LEVEL_MULTIPLIER(1f);
  func_406();
  AUDIO::UNREGISTER_SCRIPT_WITH_AUDIO();
  func_397(0);
  SCRIPT::TERMINATE_THIS_THREAD();
}