// am_armwrestling.ysc @ L124531
void func_1245(float fParam0)
{
  if (NETWORK::NETWORK_IS_GAME_IN_PROGRESS())
  {
    NETWORK::NETWORK_OVERRIDE_SEND_RESTRICTIONS_ALL(false);
    NETWORK::NETWORK_OVERRIDE_RECEIVE_RESTRICTIONS_ALL(false);
    NETWORK::NETWORK_SET_TALKER_PROXIMITY(fParam0);
    NETWORK::NETWORK_SET_TEAM_ONLY_CHAT(false);
  }
}