// fmmc_launcher.ysc @ L628753
void func_10422()
{
  PED::REMOVE_ACTION_MODE_ASSET("TREVOR_ACTION");
  PED::REMOVE_ACTION_MODE_ASSET("MICHAEL_ACTION");
  PED::REMOVE_ACTION_MODE_ASSET("FRANKLIN_ACTION");
}