// fm_mission_controller.ysc @ L326525
void func_4546()
{
  if (!func_4547() && !CAM::IS_CINEMATIC_CAM_RENDERING())
  {
    iLocal_44371 = CAM::CREATE_CAM_WITH_PARAMS("default_scripted_camera", CAM::GET_FINAL_RENDERED_CAM_COORD(), CAM::GET_FINAL_RENDERED_CAM_ROT(2), CAM::GET_FINAL_RENDERED_CAM_FOV(), false, 2);
    CAM::SET_CAM_NEAR_CLIP(iLocal_44371, CAM::GET_FINAL_RENDERED_CAM_NEAR_CLIP());
    CAM::SET_CAM_FAR_CLIP(iLocal_44371, CAM::GET_FINAL_RENDERED_CAM_FAR_CLIP());
    CAM::SET_CAM_MOTION_BLUR_STRENGTH(iLocal_44371, CAM::GET_FINAL_RENDERED_CAM_MOTION_BLUR_STRENGTH());
    CAM::SET_CAM_ACTIVE(iLocal_44371, true);
    CAM::RENDER_SCRIPT_CAMS(true, false, 3000, true, false, 0);
  }
}