// am_armwrestling.ysc @ L125605
void func_1322()
{
  if (CAM::GET_CAM_VIEW_MODE_FOR_CONTEXT(CAM::_GET_CAM_ACTIVE_VIEW_MODE_CONTEXT()) != Global_1390636)
  {
    if (CAM::_GET_CAM_ACTIVE_VIEW_MODE_CONTEXT() == 0 && Global_1390636 == 3)
    {
      Global_1390636 = CAM::GET_CAM_VIEW_MODE_FOR_CONTEXT(0);
    }
    CAM::SET_CAM_VIEW_MODE_FOR_CONTEXT(CAM::_GET_CAM_ACTIVE_VIEW_MODE_CONTEXT(), Global_1390636);
  }
}