// gb_contraband_buy.ysc @ L7743
void func_201(int iParam0, int iParam1)
{
  bool bVar0;
  int iVar1;
  
  bVar0 = false;
  iVar1 = NETWORK::NET_TO_VEH(Local_610.f_159[iParam0 /*4*/]);
  VEHICLE::SET_VEHICLE_TYRES_CAN_BURST(iVar1, false);
  VEHICLE::SET_VEHICLE_HAS_STRONG_AXLES(iVar1, true);
  VEHICLE::SET_VEHICLE_EXPLODES_ON_HIGH_EXPLOSION_DAMAGE(iVar1, false);
  VEHICLE::SET_VEHICLE_STRONG(iVar1, true);
  VEHICLE::SET_VEHICLE_AUTOMATICALLY_ATTACHES(iVar1, false, 0);
  VEHICLE::_SET_VEHICLE_DAMAGE_MODIFIER(iVar1, func_205(iParam1));
  VEHICLE::SET_VEHICLE_DOORS_LOCKED_FOR_NON_SCRIPT_PLAYERS(iVar1, true);
  func_203(iVar1);
  VEHICLE::_0x7D6F9A3EF26136A0(iVar1, bVar0, false);
  VEHICLE::SET_VEHICLE_ALLOW_NO_PASSENGERS_LOCKON(iVar1, bVar0);
  if (func_202(ENTITY::GET_ENTITY_MODEL(iVar1)))
  {
    VEHICLE::SET_VEHICLE_INDIVIDUAL_DOORS_LOCKED(iVar1, 2, 2);
    VEHICLE::SET_VEHICLE_INDIVIDUAL_DOORS_LOCKED(iVar1, 3, 2);
  }
  VEHICLE::SET_VEHICLE_DOORS_LOCKED_FOR_NON_SCRIPT_PLAYERS(iVar1, true);
  VEHICLE::_0xDBC631F109350B8C(iVar1, true);
  VEHICLE::_0x2311DD7159F00582(iVar1, true);
  VEHICLE::_0x1B212B26DD3C04DF(iVar1, false);
}