// barry1.ysc @ L40856
void func_332()
{
  if (AUDIO::IS_AUDIO_SCENE_ACTIVE(sLocal_340))
  {
    AUDIO::STOP_AUDIO_SCENE(sLocal_340);
  }
  AUDIO::CLEAR_AMBIENT_ZONE_STATE(sLocal_555, true);
  if (ENTITY::DOES_ENTITY_EXIST(Local_96.f_28[0]))
  {
    PED::DELETE_PED(&(Local_96.f_28[0]));
  }
  PLAYER::SET_PLAYER_HEALTH_RECHARGE_MULTIPLIER(PLAYER::PLAYER_ID(), 1f);
  PLAYER::SET_PLAYER_WEAPON_DAMAGE_MODIFIER(PLAYER::GET_PLAYER_INDEX(), 1f);
  PED::SET_PED_CAN_SWITCH_WEAPON(PLAYER::PLAYER_PED_ID(), true);
  PLAYER::SPECIAL_ABILITY_UNLOCK(func_33(0), 0);
  PED::SET_PED_USING_ACTION_MODE(PLAYER::PLAYER_PED_ID(), false, -1, 0);
  func_72();
  GRAPHICS::ENABLE_ALIEN_BLOOD_VFX(false);
}