// drunk.ysc @ L4370
void func_142(int iParam0, float fParam1)
{
  if (NETWORK::NETWORK_IS_GAME_IN_PROGRESS() && !NETWORK::NETWORK_HAS_CONTROL_OF_ENTITY(iParam0))
  {
    return;
  }
  if (ENTITY::IS_ENTITY_A_PED(iParam0))
  {
    PED::_0x288DF530C92DAD6F(ENTITY::GET_PED_INDEX_FROM_ENTITY_INDEX(iParam0), fParam1);
  }
  else if (ENTITY::IS_ENTITY_A_VEHICLE(iParam0))
  {
    VEHICLE::SET_VEHICLE_STEER_BIAS(ENTITY::GET_VEHICLE_INDEX_FROM_ENTITY_INDEX(iParam0), fParam1);
  }
}