// fbi5a.ysc @ L129475
void func_950()
{
  iLocal_3685 = INTERIOR::GET_INTERIOR_AT_COORDS(Local_3380);
  STREAMING::REQUEST_MODEL(Local_988[0 /*25*/].f_1);
  STREAMING::REQUEST_MODEL(Local_212[0 /*25*/].f_1);
  STREAMING::REQUEST_MODEL(Local_1959.f_2);
  STREAMING::REQUEST_MODEL(Local_2272[0 /*24*/].f_2);
  STREAMING::REQUEST_MODEL(Local_2272[1 /*24*/].f_2);
  STREAMING::REQUEST_MODEL(Local_2272[2 /*24*/].f_2);
  STREAMING::REQUEST_MODEL(WEAPON::GET_WEAPONTYPE_MODEL(joaat("weapon_carbinerifle")));
  WEAPON::REQUEST_WEAPON_ASSET(joaat("weapon_carbinerifle"), 31, 0);
  STREAMING::REQUEST_MODEL(WEAPON::GET_WEAPONTYPE_MODEL(joaat("weapon_stungun")));
  WEAPON::REQUEST_WEAPON_ASSET(joaat("weapon_stungun"), 31, 0);
  AUDIO::PREPARE_ALARM("FIB_05_BIOTECH_LAB_ALARMS");
  AUDIO::REQUEST_SCRIPT_AUDIO_BANK("SCRIPT\LIFTS", false, -1);
  STREAMING::REQUEST_ANIM_DICT("missfbi5ig_2");
  PED::REQUEST_ACTION_MODE_ASSET("MICHAEL_ACTION");
  PED::REQUEST_ACTION_MODE_ASSET("MP_FEMALE_ACTION");
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 0, 0, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 3, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 4, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 6, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 8, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 10, 0, 0);
  INTERIOR::PIN_INTERIOR_IN_MEMORY(iLocal_3685);
}