// am_mp_hangar.ysc @ L378235
void func_6244()
{
  GRAPHICS::SET_STREAMED_TEXTURE_DICT_AS_NO_LONGER_NEEDED("LineArcadeMinigame");
  AUDIO::RELEASE_NAMED_SCRIPT_AUDIO_BANK("DLC_EXEC1/OFFICE_BOARDROOM");
  HUD::CLEAR_ADDITIONAL_TEXT(3, false);
  MISC::CLEAR_BIT(&Global_1669327, 6);
  MISC::CLEAR_BIT(&Global_1669327, 7);
}