// am_mp_arena_garage.ysc @ L309831
void func_4919(var uParam0, var uParam1)
{
  if (!PLAYER::IS_PLAYER_TARGETTING_ANYTHING(PLAYER::PLAYER_ID()) && !PLAYER::IS_PLAYER_FREE_AIMING(PLAYER::PLAYER_ID()))
  {
    HUD::HIDE_HUD_COMPONENT_THIS_FRAME(2);
  }
  PAD::DISABLE_CONTROL_ACTION(0, 24, true);
  PAD::DISABLE_CONTROL_ACTION(0, 140, true);
  PAD::DISABLE_CONTROL_ACTION(0, 141, true);
  PAD::DISABLE_CONTROL_ACTION(0, 143, true);
  PAD::DISABLE_CONTROL_ACTION(0, 16, true);
  PAD::DISABLE_CONTROL_ACTION(0, 17, true);
  PAD::DISABLE_CONTROL_ACTION(0, 14, true);
  PAD::DISABLE_CONTROL_ACTION(0, 15, true);
  PAD::DISABLE_CONTROL_ACTION(0, 37, true);
  PAD::DISABLE_CONTROL_ACTION(0, 12, true);
  PAD::DISABLE_CONTROL_ACTION(0, 13, true);
  PAD::DISABLE_CONTROL_ACTION(0, 45, true);
  PAD::DISABLE_CONTROL_ACTION(0, 22, true);
  PAD::DISABLE_CONTROL_ACTION(0, 23, true);
  PAD::DISABLE_CONTROL_ACTION(0, 0, true);
  if (PAD::_IS_USING_KEYBOARD(2))
  {
    PAD::DISABLE_CONTROL_ACTION(0, 200, true);
  }
  Global_2544210.f_4031 = 1;
  Global_1660816 = 1;
  func_4920(uParam1[0], uParam0);
}