// agency_heist3a.ysc @ L134174
int func_1041()
{
  if (((((((((((((((((((((STREAMING::HAS_MODEL_LOADED(func_541(0)) && STREAMING::HAS_MODEL_LOADED(func_541(1))) && STREAMING::HAS_MODEL_LOADED(Local_1019[0 /*32*/].f_1)) && PED::HAS_PED_PRELOAD_VARIATION_DATA_FINISHED(PLAYER::PLAYER_PED_ID())) && STREAMING::HAS_MODEL_LOADED(Local_82.f_1)) && STREAMING::HAS_MODEL_LOADED(joaat("prop_phone_ing"))) && STREAMING::HAS_ANIM_DICT_LOADED(sLocal_7275)) && STREAMING::HAS_ANIM_DICT_LOADED(sLocal_7277)) && VEHICLE::HAS_VEHICLE_RECORDING_BEEN_LOADED(2, "lkagency3a")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_crew_0_0")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_crew_1_0")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_0")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_1")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_2")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_3")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_4")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_5")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_michael_6")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_ambient_0")) && TASK::GET_IS_WAYPOINT_RECORDING_LOADED("agency3a_ambient_1")) && AUDIO::REQUEST_SCRIPT_AUDIO_BANK("SCRIPT\FBI_Heist_5_Finale_02", false, -1)) && STREAMING::IS_SRL_LOADED())
  {
    return 1;
  }
  return 0;
}