// agency_heist3a.ysc @ L134365
void func_1050()
{
  AUDIO::RELEASE_NAMED_SCRIPT_AUDIO_BANK("SCRIPT\LIFTS");
  TASK::ASSISTED_MOVEMENT_REMOVE_ROUTE("jan_foyet_ft_door");
  TASK::ASSISTED_MOVEMENT_REMOVE_ROUTE("tunrs1");
  TASK::ASSISTED_MOVEMENT_REMOVE_ROUTE("tunrs2");
  TASK::ASSISTED_MOVEMENT_REMOVE_ROUTE("tunrs3");
}