// re_bus_tours.ysc @ L7439
void func_183()
{
  PLAYER::_0x36F1B38855F2A8DF(PLAYER::PLAYER_ID());
  PLAYER::_SWITCH_CRIME_TYPE(PLAYER::PLAYER_ID(), 5);
  PLAYER::_SWITCH_CRIME_TYPE(PLAYER::PLAYER_ID(), 3);
  PLAYER::_SWITCH_CRIME_TYPE(PLAYER::PLAYER_ID(), 15);
  PLAYER::_SWITCH_CRIME_TYPE(PLAYER::PLAYER_ID(), 2);
  PLAYER::_SWITCH_CRIME_TYPE(PLAYER::PLAYER_ID(), 4);
}