// nigel2.ysc @ L52112
void func_550()
{
  func_559();
  func_552(64, 2, 0);
  PLAYER::SET_WANTED_LEVEL_MULTIPLIER(0.2f);
  MISC::ENABLE_DISPATCH_SERVICE(2, false);
  MISC::ENABLE_DISPATCH_SERVICE(3, false);
  MISC::ENABLE_DISPATCH_SERVICE(4, false);
  MISC::ENABLE_DISPATCH_SERVICE(5, false);
  AUDIO::SET_AGGRESSIVE_HORNS(true);
  func_542(1);
  AUDIO::REGISTER_SCRIPT_WITH_AUDIO(0);
  func_551();
}