// am_bru_box.ysc @ L8965
void func_231()
{
  if (MISC::IS_BIT_SET(iLocal_168, 4))
  {
    PLAYER::SET_PLAYER_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 0.72f);
    PLAYER::SET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 1f, true);
    PLAYER::SET_PLAYER_WEAPON_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), 1f);
    PLAYER::SET_PLAYER_MELEE_WEAPON_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), 1f);
    func_232(1);
    MISC::CLEAR_BIT(&iLocal_168, 5);
    MISC::CLEAR_BIT(&iLocal_168, 7);
    MISC::CLEAR_BIT(&iLocal_168, 4);
  }
}