// freemode.ysc @ L1106188
void func_18657()
{
  GRAPHICS::SET_DISABLE_DECAL_RENDERING_THIS_FRAME();
  HUD::HIDE_HUD_AND_RADAR_THIS_FRAME();
  HUD::HIDE_HELP_TEXT_THIS_FRAME();
  HUD::THEFEED_HIDE_THIS_FRAME();
  HUD::HIDE_SCRIPTED_HUD_COMPONENT_THIS_FRAME(19);
  PAD::DISABLE_CONTROL_ACTION(2, 199, true);
  PAD::DISABLE_CONTROL_ACTION(2, 200, true);
  if (func_1677())
  {
    func_3098();
  }
}