// arena_carmod.ysc @ L323904
int func_2926()
{
  if (!func_1325(PLAYER::PLAYER_ID()))
  {
    return 0;
  }
  if (!PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), false))
  {
    if ((!NETWORK::NETWORK_IS_IN_MP_CUTSCENE() && !func_1459(PLAYER::PLAYER_ID())) && !Global_1683937)
    {
      MISC::CLEAR_BIT(&iLocal_1831, 4);
    }
  }
  else if ((((((((((func_2923() || !func_290(PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), false), 1)) || PAD::GET_DISABLED_CONTROL_UNBOUND_NORMAL(0, 71) != 0f) || PAD::GET_DISABLED_CONTROL_UNBOUND_NORMAL(0, 72) != 0f) || PAD::IS_CONTROL_PRESSED(0, 71)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(0, 71)) || PAD::IS_DISABLED_CONTROL_PRESSED(0, 71)) || PAD::IS_CONTROL_JUST_PRESSED(0, 72)) || PAD::IS_CONTROL_PRESSED(0, 72)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(0, 72)) || PAD::IS_DISABLED_CONTROL_PRESSED(0, 72))
  {
    return 0;
  }
  if (((((((((PED::GET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 113) || func_2923()) || PED::GET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 373)) || MISC::IS_BIT_SET(iLocal_1831, 4)) || func_2728()) || TASK::GET_SCRIPT_TASK_STATUS(PLAYER::PLAYER_PED_ID(), 451360105) == 1) || TASK::GET_SCRIPT_TASK_STATUS(PLAYER::PLAYER_PED_ID(), 451360105) == 0) || TASK::GET_IS_TASK_ACTIVE(PLAYER::PLAYER_PED_ID(), 2)) || !func_201(PLAYER::PLAYER_ID(), -1)) || !func_1674(&uLocal_1847, 3000, 0))
  {
    return 0;
  }
  return 1;
}