// freemode.ysc @ L191369
void func_2691()
{
  if (!ENTITY::IS_ENTITY_DEAD(PLAYER::PLAYER_PED_ID(), false))
  {
    PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 157, true);
    ENTITY::SET_ENTITY_HEALTH(PLAYER::PLAYER_PED_ID(), 200, 0);
  }
  PED::SET_PED_MAX_HEALTH(PLAYER::PLAYER_PED_ID(), 200);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 189, false);
  PLAYER::SET_RUN_SPRINT_MULTIPLIER_FOR_PLAYER(PLAYER::PLAYER_ID(), 1f);
  PLAYER::SET_SWIM_MULTIPLIER_FOR_PLAYER(PLAYER::PLAYER_ID(), 1f);
  PLAYER::SET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 1f, true);
  func_2692(0);
  Global_112237 = 0;
  Global_31349 = 0;
  HUD::DISPLAY_RADAR(true);
  if (!func_681(14))
  {
    HUD::THEFEED_RESUME();
  }
  PLAYER::SET_PLAYER_CAN_USE_COVER(PLAYER::PLAYER_ID(), true);
  MISC::SET_STUNT_JUMPS_CAN_TRIGGER(true);
  MISC::WATER_OVERRIDE_SET_STRENGTH(0f);
  if (Global_31501 != 0)
  {
    EVENT::REMOVE_SHOCKING_EVENT(Global_31501);
  }
}