// agency_heist1.ysc @ L111442
void func_708()
{
  if (VEHICLE::IS_VEHICLE_DRIVEABLE(iLocal_1012, false))
  {
    if (!PED::IS_PED_IN_VEHICLE(PLAYER::PLAYER_PED_ID(), iLocal_1012, false))
    {
      PED::SET_PED_INTO_VEHICLE(PLAYER::PLAYER_PED_ID(), iLocal_1012, -1);
    }
    ENTITY::SET_ENTITY_COORDS_NO_OFFSET(iLocal_1012, 72.6414f, -702.4333f, 31.18f, false, false, true);
    ENTITY::SET_ENTITY_QUATERNION(iLocal_1012, 0.0019f, 0.0174f, -0.174f, 0.9846f);
    VEHICLE::SET_VEHICLE_ON_GROUND_PROPERLY(iLocal_1012, 5f);
  }
  PED::FORCE_PED_AI_AND_ANIMATION_UPDATE(PLAYER::PLAYER_PED_ID(), false, false);
  ENTITY::SET_ENTITY_VISIBLE(PLAYER::PLAYER_PED_ID(), false, false);
  WEAPON::SET_CURRENT_PED_WEAPON(PLAYER::PLAYER_PED_ID(), joaat("weapon_unarmed"), true);
  WEAPON::HIDE_PED_WEAPON_FOR_SCRIPTED_CUTSCENE(PLAYER::PLAYER_PED_ID(), true);
  func_709(0);
  CAM::SET_CINEMATIC_BUTTON_ACTIVE(false);
}