// fm_bj_race_controler.ysc @ L123108
void func_1436(bool bParam0)
{
  OBJECT::_SET_LOCAL_PLAYER_CAN_USE_PICKUPS_WITH_THIS_MODEL(func_1441(), bParam0);
  OBJECT::_SET_LOCAL_PLAYER_CAN_USE_PICKUPS_WITH_THIS_MODEL(func_1440(), bParam0);
  OBJECT::_SET_LOCAL_PLAYER_CAN_USE_PICKUPS_WITH_THIS_MODEL(func_1439(), bParam0);
  OBJECT::_SET_LOCAL_PLAYER_CAN_USE_PICKUPS_WITH_THIS_MODEL(func_1438(), bParam0);
  OBJECT::_SET_LOCAL_PLAYER_CAN_USE_PICKUPS_WITH_THIS_MODEL(func_1437(-2), bParam0);
}