// agency_heist3b.ysc @ L114391
void func_764()
{
  AUDIO::STOP_SOUND(iLocal_3908[0]);
  AUDIO::PLAY_SOUND_FROM_COORD(iLocal_3908[1], "HACKING_DOWNLOADED", ENTITY::GET_ENTITY_COORDS(Local_3865[2 /*2*/], true), 0, false, 0, false);
  GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iLocal_71, "SET_LOADING_PROGRESS");
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(100);
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(0);
  GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
  GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iLocal_71, "SET_LOADING_MESSAGE");
  func_765("A3B_DLCOMP");
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(2);
  GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
  GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(iLocal_71, "SET_LOADING_TIME");
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(0);
  GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
  iLocal_6504 = 1;
}