// am_hunt_the_beast.ysc @ L114366
void func_840()
{
  Global_2463477 = PED::GET_PED_MAX_HEALTH(PLAYER::PLAYER_PED_ID());
  func_418();
  PED::CLEAR_PED_STORED_HAT_PROP(PLAYER::PLAYER_PED_ID());
  PED::CLEAR_ALL_PED_PROPS(PLAYER::PLAYER_PED_ID());
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 189, true);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 407, true);
  PLAYER::SET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 100f, true);
  PED::SET_PED_MAX_HEALTH(PLAYER::PLAYER_PED_ID(), Global_262145.f_11394);
  ENTITY::SET_ENTITY_HEALTH(PLAYER::PLAYER_PED_ID(), Global_262145.f_11394, 0);
  PED::SET_PED_SUFFERS_CRITICAL_HITS(PLAYER::PLAYER_PED_ID(), false);
  PED::_0x711794453CFD692B(PLAYER::PLAYER_PED_ID(), 1);
  PLAYER::_0x8D768602ADEF2245(PLAYER::PLAYER_ID(), 500f);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 410, true);
  ENTITY::SET_ENTITY_ALPHA(PLAYER::PLAYER_PED_ID(), 255, false);
  PLAYER::SET_PLAYER_VEHICLE_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), 0.5f);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 411, true);
  Global_2463474 = 0;
  func_9(&Global_2463475);
  MISC::_SET_PLAYER_IS_IN_ANIMAL_FORM(true);
  PLAYER::SET_PLAYER_LEAVE_PED_BEHIND(PLAYER::PLAYER_ID(), false);
  NETWORK::NETWORK_DISABLE_LEAVE_REMOTE_PED_BEHIND(true);
  MISC::SET_BIT(&(Global_2426865[PLAYER::PLAYER_ID() /*449*/].f_199), 29);
  func_416(1);
}