// shop_controller.ysc @ L95351
void func_658(int iParam0, bool bParam1)
{
  if (GRAPHICS::HAS_SCALEFORM_SCRIPT_HUD_MOVIE_LOADED(22))
  {
    GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(22, "SET_PLAYER_CHIP_CHANGE");
    GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(iParam0);
    GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_BOOL(bParam1);
    GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
    MISC::SET_BIT(&Global_1703158, 8);
  }
  else
  {
    GRAPHICS::REQUEST_SCALEFORM_SCRIPT_HUD_MOVIE(22);
  }
}