// fm_content_golden_gun.ysc @ L23601
void func_557(var uParam0, int iParam1, var uParam2)
{
  ENTITY::FREEZE_ENTITY_POSITION(iParam1, true);
  PED::SET_FACIAL_IDLE_ANIM_OVERRIDE(iParam1, "mood_sleeping_1", 0);
  PED::SET_PED_CAN_BE_TARGETTED(iParam1, false);
  PED::SET_PED_RELATIONSHIP_GROUP_HASH(iParam1, Global_1575021);
  PED::SET_PED_CONFIG_FLAG(iParam1, 128, false);
  PED::SET_PED_CONFIG_FLAG(iParam1, 294, true);
  PED::SET_PED_CONFIG_FLAG(iParam1, 208, true);
  PED::SET_PED_CONFIG_FLAG(iParam1, 118, false);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 0, 0, 2, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 2, 0, 0, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 4, 0, 1, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 5, 0, 0, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 6, 0, 0, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 7, 2, 0, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 9, 0, 0, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 10, 0, 0, 0);
  PED::SET_PED_COMPONENT_VARIATION(iParam1, 11, 0, 1, 0);
  PED::SET_PED_PROP_INDEX(iParam1, 1, 1, 0, false);
  AUDIO::_0xAB6781A5F3101470(iParam1, 1);
}