// fmmc_launcher.ysc @ L429835
void func_7150(bool bParam0, char* sParam1, bool bParam2, bool bParam3, char* sParam4)
{
  if (GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD_ON_FRONTEND("SET_DESCRIPTION"))
  {
    GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(iParam0);
    GRAPHICS::BEGIN_TEXT_COMMAND_SCALEFORM_STRING(sParam1);
    if (iParam3 != -1)
    {
      HUD::ADD_TEXT_COMPONENT_INTEGER(iParam3);
    }
    if (!MISC::IS_STRING_NULL_OR_EMPTY(sParam4))
    {
      HUD::ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME(sParam4);
    }
    GRAPHICS::_END_TEXT_COMMAND_SCALEFORM_STRING_2();
    GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_BOOL(bParam2);
    GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
  }
}