// freemode.ysc @ L166157
void func_2285()
{
  if (!func_2287(PLAYER::PLAYER_ID(), 8))
  {
    return;
  }
  PLAYER::SET_PLAYER_WEAPON_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), 1f);
  PLAYER::SET_PLAYER_HEALTH_RECHARGE_MULTIPLIER(PLAYER::PLAYER_ID(), 1f);
  PLAYER::_SET_PLAYER_HEALTH_RECHARGE_LIMIT(PLAYER::PLAYER_ID(), 0.5f);
  PLAYER::SET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 1f, true);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 410, false);
  PED::SET_PED_SUFFERS_CRITICAL_HITS(PLAYER::PLAYER_PED_ID(), true);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 416, false);
  HUD::_SET_ABILITY_BAR_VISIBILITY_IN_MULTIPLAYER(false);
  PLAYER::_SPECIAL_ABILITY_DEPLETE(PLAYER::PLAYER_ID(), 0);
  if (NETWORK::NETWORK_IS_GAME_IN_PROGRESS())
  {
    PLAYER::_SET_SPECIAL_ABILITY(PLAYER::PLAYER_ID(), -1, 0);
  }
  func_2286(8);
}