// fm_mission_controller.ysc @ L636838
void func_10478()
{
  PAD::DISABLE_CONTROL_ACTION(0, 24, true);
  PAD::DISABLE_CONTROL_ACTION(0, 257, true);
  PAD::DISABLE_CONTROL_ACTION(0, 25, true);
  PAD::DISABLE_CONTROL_ACTION(0, 53, true);
  PAD::DISABLE_CONTROL_ACTION(0, 54, true);
  PAD::DISABLE_CONTROL_ACTION(0, 58, true);
  PLAYER::_0xB885852C39CC265D();
  PAD::DISABLE_CONTROL_ACTION(0, 143, true);
  PAD::DISABLE_CONTROL_ACTION(0, 47, true);
  PAD::DISABLE_CONTROL_ACTION(0, 38, true);
  PAD::DISABLE_CONTROL_ACTION(0, 69, true);
  PAD::DISABLE_CONTROL_ACTION(0, 70, true);
  PAD::DISABLE_CONTROL_ACTION(0, 68, true);
  PAD::DISABLE_CONTROL_ACTION(0, 114, true);
  PAD::DISABLE_CONTROL_ACTION(0, 92, true);
  PAD::DISABLE_CONTROL_ACTION(0, 99, true);
  PAD::DISABLE_CONTROL_ACTION(0, 115, true);
}