// business_battles_sell.ysc @ L43326
void func_576(int iParam0)
{
  func_577(iParam0);
  VEHICLE::SET_VEHICLE_TYRES_CAN_BURST(iParam0, false);
  VEHICLE::SET_VEHICLE_STRONG(iParam0, true);
  VEHICLE::_SET_VEHICLE_DAMAGE_MODIFIER(iParam0, 0.2f);
  VEHICLE::_0xBB2333BB87DDD87F(iParam0, 0);
  VEHICLE::SET_VEHICLE_EXPLODES_ON_HIGH_EXPLOSION_DAMAGE(iParam0, false);
}