// family2.ysc @ L35618
void func_247(bool bParam0, float fParam1)
{
  if (bParam0)
  {
    MISC::WATER_OVERRIDE_FADE_IN(fParam1);
    MISC::WATER_OVERRIDE_SET_OCEANNOISEMINAMPLITUDE(0.35f);
    MISC::WATER_OVERRIDE_SET_OCEANWAVEAMPLITUDE(0.3f);
    MISC::WATER_OVERRIDE_SET_OCEANWAVEMINAMPLITUDE(0.25f);
    MISC::WATER_OVERRIDE_SET_OCEANWAVEMAXAMPLITUDE(0.35f);
    MISC::WATER_OVERRIDE_SET_SHOREWAVEAMPLITUDE(0.4f);
    MISC::WATER_OVERRIDE_SET_SHOREWAVEMINAMPLITUDE(0.25f);
    MISC::WATER_OVERRIDE_SET_SHOREWAVEMAXAMPLITUDE(0.55f);
    MISC::WATER_OVERRIDE_SET_RIPPLEBUMPINESS(0.45f);
    MISC::WATER_OVERRIDE_SET_RIPPLEDISTURB(0.5f);
    MISC::WATER_OVERRIDE_SET_RIPPLEMAXBUMPINESS(0.6f);
    MISC::WATER_OVERRIDE_SET_RIPPLEMINBUMPINESS(0.25f);
    MISC::WATER_OVERRIDE_SET_STRENGTH(0.75f);
  }
  else
  {
    MISC::WATER_OVERRIDE_FADE_OUT(fParam1);
  }
}