// agency_heist3a.ysc @ L141232
void func_1165()
{
  AUDIO::REGISTER_SCRIPT_WITH_AUDIO(0);
  HUD::REQUEST_ADDITIONAL_TEXT("fbiS4AU", 6);
  HUD::REQUEST_ADDITIONAL_TEXT("h1set4", 0);
  while (!HUD::HAS_ADDITIONAL_TEXT_LOADED(0) || !HUD::HAS_ADDITIONAL_TEXT_LOADED(6))
  {
    SYSTEM::WAIT(0);
  }
}