// abigail1.ysc @ L33721
void func_194(char* sParam0)
{
  HUD::BEGIN_TEXT_COMMAND_THEFEED_POST("");
  HUD::_END_TEXT_COMMAND_THEFEED_POST_MESSAGETEXT_GXT_ENTRY("CHAR_ACTING_UP", "CHAR_ACTING_UP", false, 0, "DI_FEED_CHAR", sParam0);
}