// armenian1.ysc @ L46677
void func_420()
{
  VEHICLE::SET_ALL_VEHICLE_GENERATORS_ACTIVE();
  VEHICLE::SET_NUMBER_OF_PARKED_VEHICLES(-1);
  VEHICLE::SET_GARBAGE_TRUCKS(true);
  VEHICLE::SET_ALL_LOW_PRIORITY_VEHICLE_GENERATORS_ACTIVE(true);
  VEHICLE::SET_VEHICLE_DENSITY_MULTIPLIER_THIS_FRAME(1f);
  STREAMING::SET_VEHICLE_POPULATION_BUDGET(3);
  STREAMING::SET_PED_POPULATION_BUDGET(3);
}