// rural_bank_heist.ysc @ L120005
void func_920()
{
  if (PLAYER::IS_PLAYER_PLAYING(PLAYER::PLAYER_ID()))
  {
    if (ENTITY::GET_ENTITY_MODEL(PLAYER::PLAYER_PED_ID()) != func_108(1))
    {
      PAD::DISABLE_CONTROL_ACTION(0, 22, true);
      PED::SET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 102, true);
      PED::SET_PED_ALLOWED_TO_DUCK(PLAYER::PLAYER_PED_ID(), false);
    }
    else
    {
      PED::SET_PED_ALLOWED_TO_DUCK(PLAYER::PLAYER_PED_ID(), true);
    }
    if (!iLocal_89 != PED::GET_PED_RELATIONSHIP_GROUP_HASH(PLAYER::PLAYER_PED_ID()))
    {
      PED::SET_PED_RELATIONSHIP_GROUP_HASH(PLAYER::PLAYER_PED_ID(), iLocal_89);
    }
    PED::SET_PED_STEALTH_MOVEMENT(PLAYER::PLAYER_PED_ID(), false, 0);
    PED::SET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 224, true);
    PED::SET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 200, true);
    PLAYER::REPORT_POLICE_SPOTTED_PLAYER(PLAYER::PLAYER_ID());
  }
}