// nigel1a.ysc @ L47412
void func_506(bool bParam0)
{
  int iVar0;
  
  STREAMING::REMOVE_ANIM_DICT("rcmnigel1a");
  STREAMING::REMOVE_ANIM_DICT(&cLocal_581);
  STREAMING::REMOVE_ANIM_DICT(&cLocal_589);
  STREAMING::REMOVE_ANIM_DICT(&cLocal_597);
  AUDIO::RELEASE_SCRIPT_AUDIO_BANK();
  AUDIO::UNREGISTER_SCRIPT_WITH_AUDIO();
  STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(Local_557.f_1);
  STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(Local_549.f_1);
  STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(Local_530.f_11);
  iVar0 = 0;
  while (iVar0 <= 4)
  {
    STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(Local_434[iVar0 /*19*/].f_11);
    iVar0++;
  }
  if (INTERIOR::IS_INTERIOR_READY(iLocal_259))
  {
    STREAMING::SET_INTERIOR_ACTIVE(iLocal_259, false);
    INTERIOR::UNPIN_INTERIOR(iLocal_259);
  }
  if (bParam0)
  {
    HUD::CLEAR_ADDITIONAL_TEXT(0, true);
  }
}