// fm_bj_race_controler.ysc @ L260686
void func_3298()
{
  PAD::DISABLE_CONTROL_ACTION(0, 25, true);
  PAD::DISABLE_CONTROL_ACTION(0, 69, true);
  PAD::DISABLE_CONTROL_ACTION(0, 70, true);
  PAD::DISABLE_CONTROL_ACTION(0, 114, true);
  PAD::DISABLE_CONTROL_ACTION(0, 68, true);
  PAD::DISABLE_CONTROL_ACTION(0, 24, true);
  PAD::DISABLE_CONTROL_ACTION(0, 257, true);
  PAD::DISABLE_CONTROL_ACTION(2, 230, true);
  if (PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), false))
  {
    if (VEHICLE::DOES_VEHICLE_HAVE_WEAPONS(PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), false)))
    {
      VEHICLE::DISABLE_VEHICLE_WEAPON(false, joaat("vehicle_weapon_player_laser"), PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), false), PLAYER::PLAYER_PED_ID());
    }
  }
}