// fmmc_launcher.ysc @ L102749
void func_593()
{
  func_605(0);
  TASK::SET_SCENARIO_GROUP_ENABLED("Heist_Island_Peds", false);
  HUD::_SET_TOGGLE_MINIMAP_HEIST_ISLAND(false);
  PATHFIND::_SET_AI_GLOBAL_PATH_NODES_TYPE(0);
  PLAYER::SET_MAX_WANTED_LEVEL(5);
  PLAYER::SET_WANTED_LEVEL_MULTIPLIER(1f);
  PLAYER::SET_DISPATCH_COPS_FOR_PLAYER(PLAYER::PLAYER_ID(), true);
  AUDIO::SET_AUDIO_FLAG("PlayerOnDLCHeist4Island", false);
  AUDIO::SET_AMBIENT_ZONE_LIST_STATE_PERSISTENT("AZL_DLC_Hei4_Island_Zones", false, true);
  AUDIO::SET_AMBIENT_ZONE_LIST_STATE_PERSISTENT("AZL_DLC_Hei4_Island_Disabled_Zones", true, true);
  AUDIO::RELEASE_NAMED_SCRIPT_AUDIO_BANK("DLC_HEI4/DLCHEI4_GENERIC_01");
  NETWORK::NETWORK_DISABLE_LEAVE_REMOTE_PED_BEHIND(false);
  func_603();
  func_594(1);
}