// epsilon1.ysc @ L36550
void func_292()
{
  STREAMING::REQUEST_MODEL(iLocal_149);
  STREAMING::REQUEST_MODEL(iLocal_148);
  HUD::REQUEST_ADDITIONAL_TEXT("EPS1", 0);
  STREAMING::REQUEST_ANIM_DICT(sLocal_152);
  while (((!STREAMING::HAS_ANIM_DICT_LOADED(sLocal_152) || !HUD::HAS_ADDITIONAL_TEXT_LOADED(0)) || !STREAMING::HAS_MODEL_LOADED(iLocal_149)) || !STREAMING::HAS_MODEL_LOADED(iLocal_148))
  {
    SYSTEM::WAIT(0);
  }
  PLAYER::SET_WANTED_LEVEL_MULTIPLIER(0.1f);
  OBJECT::_0xF92099527DB8E2A7(128, 0);
  func_241(&uLocal_153, 0, PLAYER::PLAYER_PED_ID(), "MICHAEL", 0, 1);
  if (func_214(PLAYER::PLAYER_PED_ID()))
  {
    func_293(PLAYER::PLAYER_PED_ID(), 0);
    WEAPON::REMOVE_ALL_PED_WEAPONS(PLAYER::PLAYER_PED_ID(), true);
  }
  func_216(1);
}