// abigail1.ysc @ L39234
void func_295()
{
  PAD::DISABLE_CONTROL_ACTION(0, 21, true);
  PAD::DISABLE_CONTROL_ACTION(0, 37, true);
  PAD::DISABLE_CONTROL_ACTION(0, 25, true);
  PAD::DISABLE_CONTROL_ACTION(0, 141, true);
  PAD::DISABLE_CONTROL_ACTION(0, 140, true);
  PAD::DISABLE_CONTROL_ACTION(0, 24, true);
  PAD::DISABLE_CONTROL_ACTION(0, 257, true);
  PAD::DISABLE_CONTROL_ACTION(0, 22, true);
  PAD::DISABLE_CONTROL_ACTION(0, 23, true);
}