// am_mp_auto_shop.ysc @ L431576
void func_6494()
{
  if (!func_6354())
  {
    AUDIO::UNLOCK_RADIO_STATION_TRACK_LIST("RADIO_36_AUDIOPLAYER", "TUNER_AP_SILENCE_MUSIC");
    AUDIO::_0x4E0AF9114608257C("RADIO_36_AUDIOPLAYER", "TUNER_AP_SILENCE_MUSIC", 0);
  }
  if (!func_6387(2))
  {
    AUDIO::_LOCK_RADIO_STATION_TRACK_LIST("RADIO_36_AUDIOPLAYER", "TUNER_AP_MIX3_PARTC");
  }
  if (!func_6387(3))
  {
    AUDIO::_LOCK_RADIO_STATION_TRACK_LIST("RADIO_36_AUDIOPLAYER", "TUNER_AP_MIX3_PARTC");
  }
}